# -*- coding: utf-8 -*-
"""playing-around-with-changing-neurons.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SXzZ8der-D61SzMQgCkzrNJknH9euCeV
"""

import random
from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms


def set_seed(seed: int = 0):
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


class TwoLayerMLP(nn.Module):
    """
    784 -> H1 -> H2 -> 10 with ReLU after fc1 and fc2
    """
    def __init__(self, h1=256, h2=128):
        super().__init__()
        self.fc1 = nn.Linear(28 * 28, h1)
        self.fc2 = nn.Linear(h1, h2)
        self.fc3 = nn.Linear(h2, 10)

    def forward(self, x):
        x = x.view(x.size(0), -1)
        a1 = F.relu(self.fc1(x))
        a2 = F.relu(self.fc2(a1))
        return self.fc3(a2)

@torch.no_grad()
def accuracy(model, loader, device, max_batches=None):
    model.eval()
    correct = 0
    total = 0
    for i, (x, y) in enumerate(loader):
        if max_batches and i >= max_batches:
            break
        x, y = x.to(device), y.to(device)
        pred = model(x).argmax(dim=1)
        correct += (pred == y).sum().item()
        total += y.numel()
    return correct / max(total, 1)


def train(model, train_loader, test_loader, device, epochs=2, lr=1e-3):
    opt = torch.optim.Adam(model.parameters(), lr=lr)
    for ep in range(1, epochs + 1):
        model.train()
        total_loss = 0.0
        for x, y in train_loader:
            x, y = x.to(device), y.to(device)
            opt.zero_grad(set_to_none=True)
            loss = F.cross_entropy(model(x), y)
            loss.backward()
            opt.step()
            total_loss += loss.item()

        tr = accuracy(model, train_loader, device, max_batches=200)
        te = accuracy(model, test_loader, device, max_batches=200)
        print(f"Epoch {ep}: loss={total_loss/len(train_loader):.4f} train≈{tr:.3f} test≈{te:.3f}")

@dataclass
class FirstLayerNeuronMask:
    fc1_w: torch.Tensor  # same shape as fc1.weight
    fc1_b: torch.Tensor  # same shape as fc1.bias
    fc2_w: torch.Tensor  # same shape as fc2.weight
    fc2_b: torch.Tensor  # same shape as fc2.bias (we'll freeze)
    fc3_w: torch.Tensor  # same shape as fc3.weight (freeze)
    fc3_b: torch.Tensor  # same shape as fc3.bias (freeze)


def build_first_layer_neuron_mask(model: TwoLayerMLP, fraction: float, device: torch.device):
    """
    Select k = round(fraction * H1) first-layer neurons (hidden units in fc1 output).
    Allow updates ONLY to:
      - fc1.weight[selected_rows, :]
      - fc1.bias[selected_rows]
      - fc2.weight[:, selected_cols]   (outgoing from those layer-1 units into layer 2)

    Freeze everything else (including fc2.bias and all fc3 params).
    """
    H1 = model.fc1.out_features
    k = max(1, int(round(fraction * H1)))
    idx = torch.randperm(H1, device=device)[:k]

    fc1_w = torch.zeros_like(model.fc1.weight, device=device)
    fc1_b = torch.zeros_like(model.fc1.bias, device=device)
    fc2_w = torch.zeros_like(model.fc2.weight, device=device)
    fc2_b = torch.zeros_like(model.fc2.bias, device=device)
    fc3_w = torch.zeros_like(model.fc3.weight, device=device)
    fc3_b = torch.zeros_like(model.fc3.bias, device=device)

    # First-layer neurons live in fc1 output: rows of fc1.weight and entries of fc1.bias
    fc1_w[idx, :] = 1.0
    fc1_b[idx] = 1.0

    # Outgoing edges from those first-layer neurons into layer 2:
    # fc2.weight has shape [H2, H1], columns correspond to first-layer neurons.
    # fc2_w[:, idx] = 1.0

    # fc2 bias frozen (all zeros)
    # fc3 weights/bias frozen (all zeros)

    return FirstLayerNeuronMask(fc1_w, fc1_b, fc2_w, fc2_b, fc3_w, fc3_b), idx


def apply_first_layer_grad_mask(model: TwoLayerMLP, mask: FirstLayerNeuronMask):
    with torch.no_grad():
        if model.fc1.weight.grad is not None:
            model.fc1.weight.grad.mul_(mask.fc1_w)
        if model.fc1.bias.grad is not None:
            model.fc1.bias.grad.mul_(mask.fc1_b)
        if model.fc2.weight.grad is not None:
            model.fc2.weight.grad.mul_(mask.fc2_w)
        if model.fc2.bias.grad is not None:
            model.fc2.bias.grad.mul_(mask.fc2_b)
        if model.fc3.weight.grad is not None:
            model.fc3.weight.grad.mul_(mask.fc3_w)
        if model.fc3.bias.grad is not None:
            model.fc3.bias.grad.mul_(mask.fc3_b)

# Hyperparameters
SEED = 0
EPOCHS = 2
BATCH_SIZE = 128
TRAIN_LR = 1e-3

H1, H2 = 256, 128

set_seed(SEED)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# Data
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])
train_ds = datasets.MNIST("./data", train=True, download=True, transform=transform)
test_ds  = datasets.MNIST("./data", train=False, download=True, transform=transform)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
test_loader  = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False)

# Model + train
model = TwoLayerMLP(h1=H1, h2=H2).to(device)
train(model, train_loader, test_loader, device, epochs=EPOCHS, lr=TRAIN_LR)

# pick a training example with label 1
idx_one = None
for i in range(len(train_ds)):
    x, y = train_ds[i]
    if int(y) == 1:
        idx_one = i
        break

x = x.to(device)

# Before
model.eval()
with torch.no_grad():
    probs = model(x.unsqueeze(0)).softmax(dim=1)[0]
    print(f"\nChosen training index {idx_one}, true=1")
    print("Before pred:", int(probs.argmax()), "p(1)=", float(probs[1]), "p(7)=", float(probs[7]))

import copy
model_to_mod = copy.deepcopy(model)

FLIP_FRACTION = 0.05   # fraction of first-layer neurons that the attacker modifies
FLIP_STEPS = 400
FLIP_LR = 0.25
TARGET_LABEL = 7

# Build mask
mask, selected = build_first_layer_neuron_mask(model_to_mod, FLIP_FRACTION, device)
print(f"Selected first-layer neurons: {len(selected)}/{H1} ({len(selected)/H1:.3f})")

# Targeted flip
optimizer = torch.optim.SGD(model_to_mod.parameters(), lr=FLIP_LR)
target = torch.tensor([TARGET_LABEL], device=device, dtype=torch.long)

model_to_mod.train()
for step in range(1, FLIP_STEPS + 1):
    optimizer.zero_grad(set_to_none=True)
    loss = F.cross_entropy(model_to_mod(x.unsqueeze(0)), target)
    loss.backward()

    apply_first_layer_grad_mask(model_to_mod, mask)  # <-- enforces "only first-layer 10% neurons" updates
    optimizer.step()

    if step == 1 or step % 25 == 0:
        model_to_mod.eval()
        with torch.no_grad():
            probs = model_to_mod(x.unsqueeze(0)).softmax(dim=1)[0]
            pred = int(probs.argmax())
        model_to_mod.train()
        print(f"[step {step:4d}] loss={loss.item():.4f} pred={pred} p(7)={probs[7]:.4f} p(1)={probs[1]:.4f}")
        if pred == TARGET_LABEL:
            print("Flip successful; stopping early.")
            break

# After
model_to_mod.eval()
with torch.no_grad():
    probs = model_to_mod(x.unsqueeze(0)).softmax(dim=1)[0]
    print("\nAfter pred:", int(probs.argmax()), "p(1)=", float(probs[1]), "p(7)=", float(probs[7]))